### ISSUE TITLE
Add Typescript API with function for getting the wallet's balance

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/seabug-contracts#4]
This repo needs to get integrated into the Seabug frontend (as an NPM package). 

It also needs an additional function added for getting the wallet balance. The required CTL functionality was added in the `seabug-deployment` in `cardano-transaction-lib` but needs to get separated out (common stuff staying in CTL and rest added here).

## TODO
- [x] Create new branch in CTL repo with required wallet balance functionality (https://github.com/Plutonomicon/cardano-transaction-lib/tree/neil/wallet-balance)
- [x] Bump CTL dependency version here to utilize the newly added wallet balance functionality
- [x] Add TypeScript API required for npm packaging
- [x] Resolve `spago build` errors caused by version bump

Note: a PR will need to be created for the `neil/wallet-balance` changes in the CTL repo. The implementation of `getWalletBalance`, however, should probably be improved to use the new `fromBytesEffect` instead of `fromBytes` function (possibly other refactoring as well).
